homework5. Combine two projects
lv211184pmi/Angular2-Transformation pull request #1
Opened 2017-05-21 06:33 UTC by lv211184pmi

2017-05-23 07:55 UTC, fullstackdb requested changes
Приложение не запускаеться.
Необходимо исправить.

Как оттворить:
1. Переходим на ветку 'homework5'
2. переходим в папку 'my-film-app'
3. устанавливаем зависимости 'yarn install` || `npm install'
4. запускаем `npm run start`

Ошибки:
- '@angular/animations'
- 'api key'

Необходимо:
установить '@angular/animations' как зависимость к проекту и добавить в package.json
поменять ключи к апи

2017-05-23 08:27 UTC, fullstackdb requested changes

2017-05-23 08:27 UTC, fullstackdb commented on hw5/my-film-app/package.json
> +    "@angular/compiler": "^4.0.0",
добавить @angular/animations

2017-05-23 08:27 UTC, fullstackdb commented on hw5/my-film-app/src/app/app.component.ts
> +  title = 'app works!';
удалить неиспользуемую переменную

2017-05-23 08:27 UTC, fullstackdb commented on hw5/my-film-app/src/app/film-items/film-items.component.ts
> +    this.filmName = "Matrix"
обговорення:
чому значення змінній присвоюється тут, в ngOnInit ?
якщо значення змінної відоме, його треба присвоювати при її ініціалізації, в строці 11

2017-05-23 08:27 UTC, fullstackdb commented on hw5/my-film-app/src/app/film-items/film-items.component.ts
> +      this.FilmItemsService.getFilms(this.filmName).subscribe(data => {
опціонально: (на даному етапі наступні пункти необовязкові але надалі вони повинні бути дотримані)
перейменувати `data` в `films`
задати тип який очікується отримати `((films: any[]) => { // code })`
перевірити дані на валідність `if(films && films.length) { // code }`
опрацювати помилки (оператор catch) `.catch((errMsg) => Observable.threw(errMsg))`

2017-05-23 08:27 UTC, fullstackdb commented on hw5/my-film-app/src/app/film-items/film-items.service.ts
> +    return this.http.get(`${this.url}${filmName}`).map(this.extractData);
TS:
необхідно вказати що саме повертає метод, приклад
```
someMethod(): any[] { return ['simple', 'example', 4, 'U'] } 
// in real world we should use specific type (Interface, model, predefined type). But for now its ok to use any type
```

форматування:
вживай оператори з нового рядка.
```
this.http.get(`${this.url}filmName`)
                .map(this.extractData)
                .filter(// some code, etc) // its example, you shouldnt use it
```

До відома:
В Angular2x параметри до запиту додаються за допомогою класу URLSearchParams. Приклад:

```
private url: string = "http://www.omdbapi.com/";

getFilms (filmName: string): Observable<any> {
         let params: URLSearchParams = new URLSearchParams();
         params.set('page', '1');
         params.set('s', filmName);
         return this.http.get(this.url, { search: params })
                                  .map(this.extractData);
```

2017-05-25 19:03 UTC, lv211184pmi reviewed
пофіксив більшість зауважень, та врахував побажання по оформленню коду. Додаток запустив.

2017-05-25 19:03 UTC, lv211184pmi commented on hw5/my-film-app/src/app/app.component.ts
> +  title = 'app works!';
done

2017-05-25 19:03 UTC, lv211184pmi commented on hw5/my-film-app/src/app/film-items/film-items.component.ts
> +    this.filmName = "Matrix"
done

2017-05-26 18:54 UTC, lv211184pmi commented on hw5/my-film-app/package.json
> +    "@angular/compiler": "^4.0.0",
добавив ключ в сервіс.

2017-05-26 18:54 UTC, lv211184pmi commented on hw5/my-film-app/src/app/film-items/film-items.component.ts
> +      this.FilmItemsService.getFilms(this.filmName).subscribe(data => {
врахую

2017-05-26 18:54 UTC, lv211184pmi commented on hw5/my-film-app/src/app/film-items/film-items.service.ts
> +    return this.http.get(`${this.url}${filmName}`).map(this.extractData);
спробував ч-з URLSearchParams , консоль почала ерорити..., вникну глибше

2017-05-29 20:34 UTC, fullstackdb approved these changes

2017-05-29 21:04 UTC, merged