Homework8 clear MVC
lv211184pmi/Angular2-Transformation pull request #2
Opened 2017-05-22 20:32 UTC by lv211184pmi

2017-05-23 08:40 UTC, fullstackdb requested changes

2017-05-23 08:40 UTC, fullstackdb commented on hw8/css/style.css
> +.site-wrapper {
Форматирование:
- отступы должны быть одинаковыми

2017-05-23 08:40 UTC, fullstackdb commented on hw8/index.html
> +		<div class="form" id="pageInput">
Общий коментарий:
Необходимо отойти от использования `id`
приучивайся использовать БЕМ методологии даже в таких маленьких решениях

2017-05-23 08:40 UTC, fullstackdb commented on hw8/js/model.js
> +                console.log("Initial data is loaded");
убрать консоль лог

2017-05-23 08:40 UTC, fullstackdb commented on hw8/js/view.js
> +                let newFilm = event.target.closest(".search-film");
Добавить валидацию значения инпута

2017-05-23 08:40 UTC, fullstackdb commented on hw8/js/view.js
> +                pageInput: document.querySelector("#pageInput")
стараться работать с DOM через классы (стараться использовать БЕМ методологию - https://uk.bem.info/)

2017-05-25 19:31 UTC, lv211184pmi commented on hw8/js/model.js
> +                console.log("Initial data is loaded");
done

2017-05-25 19:33 UTC, lv211184pmi commented on hw8/css/style.css
> +.site-wrapper {
fixed

2017-05-26 20:20 UTC, lv211184pmi commented on hw8/js/view.js
> +                let newFilm = event.target.closest(".search-film");
done

2017-05-26 20:27 UTC, lv211184pmi commented on hw8/index.html
> +		<div class="form" id="pageInput">
перейменував згідно БЕМ-методології. Цікавий підхід..

2017-05-26 20:28 UTC, lv211184pmi commented on hw8/js/view.js
> +                pageInput: document.querySelector("#pageInput")
ознайомився з підходом, пізнавально. Дякую за лінку

2017-05-28 20:54 UTC, fullstackdb approved these changes

2017-05-29 10:57 UTC, merged